plugins {
    id 'net.fabricmc.fabric-loom' version '1.7-SNAPSHOT'
}

version = '1.0.0'
group = 'com.alphanostalgia'

base {
    archivesName = "alpha-nostalgia"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

repositories {
    mavenCentral()
    maven { url = "https://fabricmc.net" }
}

dependencies {
    minecraft "com.mojang:minecraft:26.3"
    mappings loom.officialMojangMappings() 
    
    modImplementation "net.fabricmc:fabric-loader:0.16.0"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.13+26.3"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
}
