name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
          
      - name: Install Build Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          
      - name: Compile Jar File
        run: gradle build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlphaNostalgia-Jar
          path: build/libs/*.jar
