name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.12-jdk25 # Merges the build tools with Java 25 smoothly
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile Client Jar
        run: gradle jar --no-daemon
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlphaNostalgia-Jar
          path: build/libs/*.jar
